name: fish_ebook
description: A multi-page fish e-book with background music, built in Flutter.
publish_to: "none"               # 私人專案不上傳 pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.0.0
  shared_preferences: ^2.0.15

  # ---- Day 1 新增核心套件 ----
  just_audio: ^0.10.4            # 背景音樂播放器 :contentReference[oaicite:0]{index=0}
  smooth_page_indicator: ^1.2.1  # 分頁指示器 :contentReference[oaicite:1]{index=1}

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  # ---- 註冊靜態資源 ----
  assets:
    - assets/images/
    - assets/audio/
